from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.freight_exchange_response_meta import FreightExchangeResponseMeta
    from ..models.problem_invalid_params_item import ProblemInvalidParamsItem


T = TypeVar("T", bound="Problem")


@_attrs_define
class Problem:
    """
    Attributes:
        detail (str | Unset): A human readable explanation specific to this occurrence of the problem that is helpful to
            locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not
            suited for non technical stakeholders and not localized.
             Example: some description for the error situation.
        instance (str | Unset): A URI reference that identifies the specific occurrence of the problem, e.g. by adding a
            fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the
            source code.
             Example: /some/uri-reference#specific-occurrence-context.
        invalid_params (list[ProblemInvalidParamsItem] | Unset): A list of invalid input parameters for this problem.
        meta (FreightExchangeResponseMeta | Unset):
        status (int | Unset): The HTTP status code generated by the origin server for this occurrence of the problem.
        title (str | Unset): A short summary of the problem type. Written in English and readable for engineers, usually
            not suited for non technical stakeholders and not localized.
             Example: some title for the error situation.
        type_ (str | Unset): A URI reference that uniquely identifies the problem type only in the context of the
            provided API. Opposed to the specification in RFC-7807, it is neither recommended to be dereferenceable and
            point to a human-readable documentation nor globally unique for the problem type.
             Default: 'about:blank'. Example: /some/uri-reference.
    """

    detail: str | Unset = UNSET
    instance: str | Unset = UNSET
    invalid_params: list[ProblemInvalidParamsItem] | Unset = UNSET
    meta: FreightExchangeResponseMeta | Unset = UNSET
    status: int | Unset = UNSET
    title: str | Unset = UNSET
    type_: str | Unset = "about:blank"
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        detail = self.detail

        instance = self.instance

        invalid_params: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.invalid_params, Unset):
            invalid_params = []
            for invalid_params_item_data in self.invalid_params:
                invalid_params_item = invalid_params_item_data.to_dict()
                invalid_params.append(invalid_params_item)

        meta: dict[str, Any] | Unset = UNSET
        if not isinstance(self.meta, Unset):
            meta = self.meta.to_dict()

        status = self.status

        title = self.title

        type_ = self.type_

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if detail is not UNSET:
            field_dict["detail"] = detail
        if instance is not UNSET:
            field_dict["instance"] = instance
        if invalid_params is not UNSET:
            field_dict["invalid-params"] = invalid_params
        if meta is not UNSET:
            field_dict["meta"] = meta
        if status is not UNSET:
            field_dict["status"] = status
        if title is not UNSET:
            field_dict["title"] = title
        if type_ is not UNSET:
            field_dict["type"] = type_

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.freight_exchange_response_meta import FreightExchangeResponseMeta
        from ..models.problem_invalid_params_item import ProblemInvalidParamsItem

        d = dict(src_dict)
        detail = d.pop("detail", UNSET)

        instance = d.pop("instance", UNSET)

        _invalid_params = d.pop("invalid-params", UNSET)
        invalid_params: list[ProblemInvalidParamsItem] | Unset = UNSET
        if _invalid_params is not UNSET:
            invalid_params = []
            for invalid_params_item_data in _invalid_params:
                invalid_params_item = ProblemInvalidParamsItem.from_dict(invalid_params_item_data)

                invalid_params.append(invalid_params_item)

        _meta = d.pop("meta", UNSET)
        meta: FreightExchangeResponseMeta | Unset
        if isinstance(_meta, Unset):
            meta = UNSET
        else:
            meta = FreightExchangeResponseMeta.from_dict(_meta)

        status = d.pop("status", UNSET)

        title = d.pop("title", UNSET)

        type_ = d.pop("type", UNSET)

        problem = cls(
            detail=detail,
            instance=instance,
            invalid_params=invalid_params,
            meta=meta,
            status=status,
            title=title,
            type_=type_,
        )

        problem.additional_properties = d
        return problem

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
